name: Post A Build Event
description: Posts a build event to Build Engine
inputs:
  credentialsJson:
    description: The credentials JSON for Build Engine
    required: true
  message:
    description: The message to post
    required: true
  component:
    description: The component to post
    required: false
runs:
  using: node24
  main: ../../dist/event.js
